server:
  port: 8087

spring:
  application:
    name: promotion-service
  datasource:
    url: "jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:ecommerce_promotion_db}?createDatabaseIfNotExist=true&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8"
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    listener:
      ack-mode: manual_immediate
    consumer:
      group-id: promotion-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8083/realms/ecommerce-realm}

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
      lastName: ECommerce
    database:
      schema-update: false
    history-level: full
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false

eureka:
  client:
    jersey:
      enabled: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  health:
    camunda:
      enabled: false
