import React from "react";

// Deploy metadata only — BPMN process key is generated by promotion-service on create.
export default function DeployModal({ open, editingId, form, onChangeForm, onClose, onSubmit }) {
  if (!open) return null;

  const patch = partial => onChangeForm({ ...form, ...partial });

  // BUG FIX: previously only `required` was enforced on start/end date - nothing stopped an
  // admin from deploying a campaign with endDate <= startDate. findClientValidationErrors()
  // validates the workflow graph, not this deploy form, so this range check never ran anywhere.
  const dateRangeInvalid = Boolean(form.startDate) && Boolean(form.endDate) && form.endDate <= form.startDate;

  const handleSubmit = e => {
    if (dateRangeInvalid) {
      e.preventDefault();
      return;
    }
    onSubmit(e);
  };

  return (
    <div className="cb-modal-overlay" onClick={onClose}>
      <div className="cb-modal" onClick={e => e.stopPropagation()}>
        <div className="cb-modal-header">
          <h2>
            {editingId
              ? "💾 Cập Nhật Chiến Dịch #" + editingId
              : "🚀 Triển Khai Chiến Dịch Lên Camunda"}
          </h2>
          <button className="cb-btn cb-btn-secondary cb-btn-sm" onClick={onClose}>✕</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="cb-fg">
            <label>Tên chiến dịch *</label>
            <input
              type="text"
              required
              value={form.name}
              placeholder="VD: Đăng ký mới — email chào mừng"
              onChange={e => patch({ name: e.target.value })}
            />
            {!editingId && (
              <small>Mã quy trình Camunda sẽ do hệ thống tự sinh từ tên (không cần nhập).</small>
            )}
          </div>

          <div className="cb-form-row">
            <div className="cb-fg">
              <label>Thời gian bắt đầu *</label>
              <input
                type="datetime-local"
                required
                value={form.startDate}
                onChange={e => patch({ startDate: e.target.value })}
              />
            </div>
            <div className="cb-fg">
              <label>Thời gian kết thúc *</label>
              <input
                type="datetime-local"
                required
                min={form.startDate || undefined}
                value={form.endDate}
                onChange={e => patch({ endDate: e.target.value })}
              />
            </div>
          </div>
          {dateRangeInvalid && (
            <small style={{ color: "#dc2626", display: "block", marginTop: -8, marginBottom: 8 }}>
              Thời gian kết thúc phải sau thời gian bắt đầu.
            </small>
          )}

          <div className="cb-modal-actions">
            <button type="button" className="cb-btn cb-btn-secondary" onClick={onClose}>
              Hủy Bỏ
            </button>
            <button type="submit" className="cb-btn cb-btn-primary" disabled={dateRangeInvalid}>
              {editingId ? "💾 Xác Nhận Cập Nhật" : "🚀 Xác Nhận & Triển Khai"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
