server:
  port: 8085

spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: "jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:ecommerce_user_db}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8"
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8083/realms/ecommerce-realm}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:ecommerce_user_nosql}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minio}
  secret-key: ${MINIO_SECRET_KEY:12345678a@}
  bucket-name: ${MINIO_BUCKET_NAME:user-avatars}

keycloak:
  admin:
    server-url: ${KEYCLOAK_ADMIN_URL:http://localhost:8083}
    realm: ${KEYCLOAK_REALM:ecommerce-realm}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:ecommerce-backend}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:ZAyFzRoBJY8nWNg5dN5XMc3fRngDIei6}

location:
  api-url: ${LOCATION_API_URL:https://provinces.open-api.vn/api/v2}
